name: Aggregate & FTP Deploy

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run aggregate

            - name: FTP Deploy
            uses: SamKirkland/FTP-Deploy-Action@v4.3.6
            with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              local-dir: public
              server-dir: ${{ secrets.FTP_DIR }}
        
       
